### ISSUE TITLE
In-game Menu bug

### ISSUE THREAD

**Issue by SeedBoot** [TobiasBielefeld/Simple-Solitaire#55] opened 2017-07-28 12:26 UTC
Hey! Love the game. However I've noticed there's an issue when restarting the game, or returning to the main menu.

Often when tapping: **Menu > Start new game** OR: **Menu > Return to main menu**, the Menu window disappears and nothing happens!

**Comment by TobiasBielefeld** [comment] 2017-07-30 18:58
hi, thanks for the issue report!

There is one line in my code, which causes a null-pointer exception, so the menu just closes to not crash the whole application. But sadly I don't know which statement in that one line causes the exception and it never happens on my phone, so I can't reproduce it...

Could you please give me some more information about it? Like did you do something special, when the issue appeared? Rotating the display, resuming the game from a longer pause, or something like that. And did the buttons work after pressing them again? 

And could you also try to trigger this issue when pressing **Menu > Redeal**? If this button doesn't cause it, I would know where exactly the issue is :D

**Comment by SeedBoot** [comment] 2017-07-31 08:50
Hmm, that's a shame that you can't reproduce it yourself... Guess I'll have to play it some more!

I've done nothing out of the ordinary. The screen has been in portrait mode, but just straight from finishing a game. The second time the buttons are pressed it completes the action.

I will find out about the redeal button today and let you know!

Another thing I've noticed is if I choose **Return to main menu**, and then return to the game, the game is in the same state - finished, with an empty board (or unfinished if I get a bad hand!). Perhaps would it be a good idea to start a new game as the player exits the game type? So when they next return a new game is ready.

**Comment by SeedBoot** [comment] 2017-07-31 14:41
Ok, so: Mod3

If you finish a game, when prompted with the menu press **Return to main menu**. Screen flashes white then goes back to an empty game.
**Give cards again** & **Start new game** seems to be fine, when I just checked them...

**Comment by TobiasBielefeld** [comment] 2017-07-31 19:29
To the error in Mod3: This affected every game, when rotating the screen and then pressing **Return to main menu**. But I could fix it :D 

I also changed the behavior for returning to a finished game: It will now start a new game. But for unfinished games: I can't detect if the game is still winnable, so what if the player wants to continue playing that game type after a break? So for unfinished games, no new game will be started.

And I'll look at the "Menu window disappearing bug" in the next days :)

**Comment by TobiasBielefeld** [comment] 2017-08-09 08:29
could you test the new app version 3.8 if the menu bug still appears?

**Comment by SeedBoot** [comment] 2017-08-09 08:33
I'll see what I can do ;)

**Comment by SeedBoot** [comment] 2017-08-11 15:49
Hey, it's looking good from what I can tell. Will open a new issue if I find anything :)

**Comment by TobiasBielefeld** [comment] 2017-08-13 17:30
Thats nice :D I'll close this then

**Closed by TobiasBielefeld** 2017-08-13 17:30 UTC
