### ISSUE TITLE
display bug

### ISSUE THREAD

**Issue by emdete** [TobiasBielefeld/Simple-Solitaire#51] opened 2017-05-29 11:58 UTC
after moving a pile of 4 cards with a king on top from right-most to empty left-most the jack animated back to the right on top of the newly visible king there.

it stayed there even when i moved and removed cards there.

it animated back to the left when i put cards on the left-most pile. 

![screenshot](https://mister-muffin.de/p/Dg2V.png)

**Comment by TobiasBielefeld** [comment] 2017-05-30 08:26
Thanks for the report! I tried to reproduce the error with the same card layout, but it didn't work. 

The Jack was successfully moved to the left most stack,  but somehow the animation used the old coordinates...

I try to find the error here in the next time, did it appear more than once? Because I play my game quite often, but this never happened to me.

**Comment by emdete** [comment] 2017-06-01 09:38
yes, i play it often as well but it only happened once. i've never ever seen any kind of screen display problems (or any problem). that's why i was so confused.

**Comment by TobiasBielefeld** [comment] 2017-06-03 17:37
Gladly the bug doesn't really break the game play. Well i will try to fix it :)

**Comment by emdete** [comment] 2017-06-13 09:05
first i thought it's just an easter egg because i played it too often (and too bad) :D

**Comment by TobiasBielefeld** [comment] 2017-06-16 22:07
It's definitely not an easter egg :D Maybe I just found a part of code, where the issue could be caused... stay tuned :D

**Comment by TobiasBielefeld** [comment] 2017-12-26 12:41
I don't know if you still follow this, but I finally found the problem and could fix it in the newest update :) So I can finally close this issue

**Closed by TobiasBielefeld** 2017-12-26 12:41 UTC

**Comment by emdete** [comment] 2017-12-27 13:09
yes, i look into it from time to time. and i never again saw that bug. thanks for notifying!
